// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Final_System/biz"
	"Final_System/data"
	"Final_System/service"
	"github.com/gin-gonic/gin"
)

import (
	_ "github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *gin.Engine {
	dataData := data.NewData()
	userData := data.NewUserData(dataData)
	userBiz := biz.NewUserBiz(userData)
	userService := service.NewUserService(userBiz)
	adminData := data.NewAdminData(dataData)
	adminBiz := biz.NewAdminBiz(adminData)
	adminService := service.NewAdminService(adminBiz)
	app := &App{
		UserService:  userService,
		AdminService: adminService,
	}
	engine := initGenEngine(app)
	return engine
}
